import { useState } from "react";
import "./App.css";

/* https://docs.pmnd.rs/react-three-fiber/getting-started/introduction */
import { Canvas, GroupProps } from "@react-three/fiber";
import { OrbitControls, Stage, useGLTF } from "@react-three/drei";

function App() {
  const [display3dScene, setDisplay3dScene] = useState(false);
  const toggleDisplay3dScene = () => setDisplay3dScene((ds) => !ds);
  return (
    <div className="flex flex-col h-full p-6 relative">
      <Hero toggleDisplay3dScene={toggleDisplay3dScene} />
      <div
        className={`${
          display3dScene ? "top-0" : "top-full"
        } absolute left-0 h-full w-full transition-all bg-sky-400`}
      >
        <Nav toggleDisplay3dScene={toggleDisplay3dScene} />
        <Canvas shadows camera={{ position: [4, 3, 8], fov: 35 }}>
          <Stage
            intensity={0.5}
            adjustCamera
            preset="rembrandt"
            environment="city"
            shadows={{
              type: "accumulative",
              color: "skyblue",
              colorBlend: 2,
              opacity: 2,
            }}
          >
            <Desk scale={[1, 1, 1]} rotation-y={Math.PI * 0.5} />
          </Stage>
          <OrbitControls
            minPolarAngle={0}
            maxPolarAngle={Math.PI / 1.9}
            makeDefault
          />
        </Canvas>
      </div>
    </div>
  );
}

/*
  Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
function Desk(props: GroupProps) {
  const { nodes, materials } = useGLTF("/table.glb") as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table_Large_Rectangular_01_Circle004.geometry}
        material={materials["795548"]}
      />
    </group>
  );
}

function Nav({ toggleDisplay3dScene }: { toggleDisplay3dScene: () => void }) {
  return (
    <nav>
      <ul className="flex justify-end gap-3 max-w-5xl mx-auto">
        <li>
          <button onClick={toggleDisplay3dScene}>Home</button>
        </li>
        <li>
          <button>Contact</button>
        </li>
      </ul>
    </nav>
  );
}

function Hero({ toggleDisplay3dScene }: { toggleDisplay3dScene: () => void }) {
  return (
    <section className="h-full flex items-center">
      <div className="flex flex-col gap-2">
        <h1 className="text-4xl">Hello, my name is Marcus</h1>
        <p className="text-lg">I am a fullstack developer studying at SFU</p>
        <ul className="flex flex-wrap gap-2 text-base">
          <li>
            <button>Download Resume</button>
          </li>
          <li>
            <button onClick={toggleDisplay3dScene}>View Projects</button>
          </li>
          <li>
            <button>Contact</button>
          </li>
        </ul>
        {/* Add github and linked in links or when hit contact pop modal? */}
      </div>
    </section>
  );
}

export default App;
