/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";
import { Group } from "three";

export default function Drink(props: GroupProps) {
  const group = useRef<Group>(null);
  const { nodes, materials } = useGLTF("/drink.gltf") as any;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_soda.geometry} material={materials.purple} />
      <mesh
        geometry={nodes.Mesh_soda_1.geometry}
        material={materials._defaultMat}
      />
    </group>
  );
}
