/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";
import { Group } from "three";

export default function Plant(props: GroupProps) {
  const group = useRef<Group>(null);
  const { nodes, materials } = useGLTF("/plant.gltf") as any;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.plant001.geometry}
        material={materials["Material.028"]}
      >
        <mesh
          geometry={nodes.NurbsPath008.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.NurbsPath010.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Circle001.geometry}
          material={materials["Material.030"]}
        />
        <mesh
          geometry={nodes.NurbsPath009.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          geometry={nodes.NurbsPath007.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.NurbsPath006.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          geometry={nodes.NurbsPath011.geometry}
          material={materials["Material.002"]}
        />
      </mesh>
    </group>
  );
}
