/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";

export function Rug(props: GroupProps) {
  const { nodes, materials } = useGLTF("./rug.glb") as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Modern_rug_Plane004-Mesh"].geometry}
        material={materials["78909C"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Modern_rug_Plane004-Mesh_1"].geometry}
        material={materials["455A64"]}
      />
    </group>
  );
}

useGLTF.preload("./rug.glb");
